# Generated by Django 2.0.7 on 2018-07-25 19:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20180725_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 25, 19, 27, 58, 713032, tzinfo=utc), verbose_name='date published'),
        ),
    ]
